apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: akshay
spec:
  groups:
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZqQ0NBVDRDQVFBd0VURVBNQTBHQTFVRUF3d0dZV3R6YUdGNU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRgpBQU9DQVE4QU1JSUJDZ0tDQVFFQXlOYmRhbUsvUlFHZ1hCYkdiY2Y3TXJ1T2IzcnpEZjFaSVI2QURTWUExZm40CnpOQ1c4Z2t6cHUrVS94em5Nay82Qk5RbUlOV3NRVC9JZWRyVytzKzVxOUpSeWI2WDczTms3VVVQTldLWnZBREwKNHV0QXl2TE5jaUxKSlFsamhIcXAvb0tXRk03QjJWYXN2b3I5RHJvVFdVS0RTM1FXemM0NmdjUmJxbURSZXU0aQpQbUlMNm9GUUhjNng5UFo3d2NNNXdtd1B6ckRaOWQ5UzVNSG1kUEtNU0VHSTRCYjhEdFk3R05QQ2M4T25CaXRwCjk3cERnQWdyKzdxdENWU3JyMVNLdE10TGVjdUEzRXBxVCtDSm1ISFMvNkhCOFAzTjNTbjFRYldyNGZEQUl3bnEKZEZiYXZGdlFaN2JkcXY4cDhDM2ZOTnlkY2k2RFptZ01ka0ZsUkV5TDh3SURBUUFCb0FBd0RRWUpLb1pJaHZjTgpBUUVMQlFBRGdnRUJBR0RKU2VzOEZyclVqTWFPRTlPK2d4TGlReVpWMWFiNjY0QjlocndYejcvclFtZUtMakNqCjdPTU1aK3BIK2pnN01LZXA1RXgvc1dwUU1aNGE4VEgvNXNhb0V5VE1mSmNqejdsSCt1WVNieGJrTENyRndPS1QKQmJGVnFWdm9ab3VKejhCaUVmZVpZcWVqY2V0MzRiS1FjL0hSdnZvT0Fqd1lWUDNUZlFBS25jdmM3ZzQvbWRRegpQa1UxUWdMSlFLZ2VYbmlnNHkrWjgyRS80N3hLWHRDeGNYdXNYdGxEM0c0SVJWdmZ6eTZhMjdkS3VkQjdtRGhpCjdncjRBU0l0Nzc3cmZaVUlPQm5qNDAvM0lNT1Z4K05KY01nemY3S2RzYXZBeThQYk4wM1owdDlDditmS1dHejQKTHNSYzE0djcxSUVJL092VzM0bUJmdUczU2lDOWJwMStjUUk9Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=  #get this key from file.key | base64 OR file.csr
  usages:
  - digital signature
  - key encipherment
  - server auth
